[build]
  publish = "dist"
  command = "echo 'Deploying static files only'"

[[redirects]]
  from = "/api/*"
  to = "https://quantumviz-agent.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist"